### ISSUE TITLE
I want to take over the npm release of this package.

### ISSUE THREAD

**Issue by septs** [KyleAMathews/toml-loader#1]

**Comment by KyleAMathews** [comment]
Is there something that needs changed?

**Comment by septs** [comment]
1. https://npmjs.com/toml-loader add maintainer [septs](https://www.npmjs.com/~septs)
I am going to release.
2. Update this repository README
Redirect user to https://github.com/NiceLabs/toml-loader
3. You're still the **Owner** can always **get back control**.
I will act as a maintainer

------------------------------------------

https://github.com/NiceLabs/toml-loader new implementation

1. support webpack 4
2. enhanced exception handling
3. follow up on the https://npmjs.com/toml update

**Comment by septs** [comment]
**@nice-labs/toml-loader** stage release:
https://npm.septs.me/#/detail/@nice-labs/toml-loader
